services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Asia/Singapore
    ports:
        - "8443:8443"
        - "8123:8123" # DYNMAP
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ./data/backups:/crafty/backups
        - ./data/logs:/crafty/logs
        - ./data/servers:/crafty/servers
        - ./data/config:/crafty/app/config
        - ./data/import:/crafty/import
