services:
  soju:
    restart: always
    container_name: soju
    build:
      context: .
      dockerfile: soju.dockerfile
    ports:
      - "6667:6667"
      - "3030:3030"
    volumes:
      - ./soju.conf:/etc/soju/config:ro
      - ./data:/soju

  # caddy:
  #   restart: always
  #   container_name: caddy
  #   build: /path/to/caddy/dockerfile
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "6697:6697"
  #   volumes:
  #     - /path/to/Caddyfile:/etc/caddy/Caddyfile
  #     - /path/to/layer4.json:/etc/caddy/layer4.json
  #     - /path/to/gamja:/www/gamja
  #     - caddy-data:/data
  #     - caddy-config:/config
