---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Management:
    - Uptime Kuma:
        icon: uptime-kuma
        href: http://192.168.31.102:9000/
        description: A fancy self-hosted monitoring tool.
